language: ruby
rvm:
  - 2.0.0
  - 1.9.3  
#  - jruby-19mode
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database puntificate_test;' -U postgres
  - rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000
bundler_args: --without development
script: 'rake spec && bundle exec rake qunit:test'
after_success: 'cap deploy'
notifications:
  email: false

#language: ruby
#rvm:
#  - 1.9.3
#  - 2.0.0
#before_script:
#  - cp config/database.yml.development-sample config/database.yml
#  - cp config/redis.yml.sample config/redis.yml
#  - psql -c 'create database discourse_test;' -U postgres
#  - rake db:migrate
#  - export RUBY_GC_MALLOC_LIMIT=50000000
#bundler_args: --without development
#script: 'rake spec && bundle exec rake qunit:test'
#services:
#  - redis-server